## Python Assignment: Data Structures, Functions, Numpy & Pandas

### Section A: Data Structures & Control Structures

##### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

numbers.append(60)
print("After append(60):", numbers)

numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

numbers.insert(2, 25)  # Insert 25 at index 2
print("After insert(2, 25):", numbers)
numbers.remove(40)

print("After remove(40):", numbers)
popped = numbers.pop()  # Removes last element
print("After pop():", numbers, "| Popped element:", popped)

copy_list = numbers.copy()   # Copy for later operations
numbers.clear()
print("After clear():", numbers)
numbers = copy_list  
print("Index of 25:", numbers.index(25))

numbers.append(20)  # Add duplicate for demonstration
print("List after adding another 20:", numbers)
print("Count of 20:", numbers.count(20))

numbers.sort()
print("After sort():", numbers)

numbers.reverse()
print("After reverse():", numbers)

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70] | Popped element: 80
After clear(): []
Index of 25: 2
List after adding another 20: [10, 20, 25, 30, 50, 60, 70, 20]
Count of 20: 2
After sort(): [10, 20, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 20, 10]


##### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [4]:
# Create a tuple of 3 student names
students = ("Himani", "Harshada", "Heena")
print("Original tuple:", students)

try:
    students[1] = "Neha"   
except TypeError as e:
    print("Error:", e)

Original tuple: ('Himani', 'Harshada', 'Heena')
Error: 'tuple' object does not support item assignment


##### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [5]:
numbers = {100, 200, 300, 200, 400, 100, 500}
print("Set:", numbers)

Set: {400, 100, 500, 200, 300}


##### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [7]:
# Create a dictionary
student = {
    "name": "Himani",
    "age": 23,
    "city": "Pune"
}

print("Original dictionary:", student)

# Update the age
student["age"] = 24

# Add a new key 'email'
student["email"] = "himani123@gmail.com"

# Print the final dictionary
print("Final dictionary:", student)

Original dictionary: {'name': 'Himani', 'age': 23, 'city': 'Pune'}
Final dictionary: {'name': 'Himani', 'age': 24, 'city': 'Pune', 'email': 'himani123@gmail.com'}


##### 5 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [8]:
# Voting eligibility check
age = 17   
# Check eligibility
if age >= 18:
    print("Yes You are eligible to vote.")
else:
    print(" No You are not eligible to vote. You must be at least 18 years old.")

 No You are not eligible to vote. You must be at least 18 years old.


##### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [9]:
marks = 82   

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "Fail"

print(f"Marks: {marks} → Grade: {grade}")

Marks: 82 → Grade: B


##### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [12]:
num = -29   
if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is negative.


##### Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [13]:
import numpy as np

scalar = np.array(5)
print("Scalar (0-D array):", scalar)

arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D array:\n", arr_2d)

Scalar (0-D array): 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


##### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [14]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
arr = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Integer Array (0–100):\n", arr)

4x4 Random Integer Array (0–100):
 [[64 35 28 38]
 [ 7 39 55 31]
 [60 88  6 23]
 [30 55 80 77]]


##### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [16]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Convert NumPy array into a Pandas DataFrame with column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print("NumPy Array:\n", arr)
print("\nPandas DataFrame:\n", df)

NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Pandas DataFrame:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


##### Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [17]:
import pandas as pd
import numpy as np

# Create a small DataFrame manually with 10 rows
data = {
    "Name": ["Himani", "Riya", "Sohan", "Neha", "Amit", 
             "Kiran", "Meena", "Ravi", "Riya", "Sohan"],
    "Age": [25, 30, 22, 28, 25, 35, 29, 40, 30, 22],
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Pune", 
             "Delhi", "Mumbai", "Chennai", "Mumbai", "Delhi"],
    "Salary": [50000, 60000, np.nan, 55000, 50000, 
               65000, 70000, np.nan, 60000, 45000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# 1. Use .info()
print("\nDataFrame Info:")
print(df.info())

# 2. Use .describe()
print("\nDataFrame Description:")
print(df.describe())

# 3. Select 'Name' and 'City' columns
print("\nSelecting 'Name' and 'City' columns:\n", df[['Name', 'City']])

# 4. Drop 'City' column
df_no_city = df.drop(columns=['City'])
print("\nDataFrame after dropping 'City' column:\n", df_no_city)

# 5. Fill missing values in 'Salary' with mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print("\nDataFrame after filling missing 'Salary' values with mean:\n", df)

# 6. Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_no_duplicates)




Original DataFrame:
      Name  Age     City   Salary
0  Himani   25     Pune  50000.0
1    Riya   30   Mumbai  60000.0
2   Sohan   22    Delhi      NaN
3    Neha   28     Pune  55000.0
4    Amit   25     Pune  50000.0
5   Kiran   35    Delhi  65000.0
6   Meena   29   Mumbai  70000.0
7    Ravi   40  Chennai      NaN
8    Riya   30   Mumbai  60000.0
9   Sohan   22    Delhi  45000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame Description:
             Age       Salary
count  10.000000      8.00000
mean   28.600000  56875.00000
std     5.660781   8425.09008
min    22.000000  45000.00000
25%    25.000000  50000.00000
